### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Green-Wolf** [pdaddyo/soundbounce-v2#68]
Hey, thanks very much for making this available for free, i had a couple of questions:

1) Is it possible to create a private room (with a password?)

2) How this connect to rooms, are you hosting a central server somewhere? 

3) Is it possible to set this up so that 1 Spotify premium account can share the live music with people that don't have spotify or are just on the free version?

Many thanks

**Comment by pdaddyo** [comment]
1. Private rooms are planned eventually, I will open an issue now to track it
2. Yes the v2.soundbounce.org is hosted by me
3. Unfortunately Spotify don't allow Connect to work with premium which means we can't control their players.  In v1 we had a workaround using YouTube but it's not perfect.

Thanks

**Comment by Green-Wolf** [comment]
Sorry i'm a bit confused by your 3rd answer. Does every person joining a room need Spotify premium or not?

**Comment by pdaddyo** [comment]
Yes we can't control any Spotify player (so have them listen along) without premium.  This is Spotify's decision: https://www.spotify.com/bg/connect/
